### ISSUE TITLE
main启动报错can only concatenate list (not "type") to list

### ISSUE THREAD

**Issue by Mobius-han** [xuwenxue000/PJ_PREDICT_IMG#6]
2019-09-05 19:56:33.128456: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "E:/AI/PJ_PREDICT_IMG/api_invoice/main.py", line 16, in <module>
    import api_invoice.service.img as img
  File "E:\AI\PJ_PREDICT_IMG\api_invoice\service\img.py", line 25, in <module>
    import api_invoice.dao.invoice_dao as invoice_dao
  File "E:\AI\PJ_PREDICT_IMG\api_invoice\dao\invoice_dao.py", line 2, in <module>
    import api_invoice.config.db as db_config
  File "E:\AI\PJ_PREDICT_IMG\api_invoice\config\db.py", line 3, in <module>
    import torndb
  File "C:\Users\yuanxiuhan\AppData\Local\Programs\Python\Python37\lib\site-packages\torndb.py", line 260, in <module>
    CONVERSIONS[field_type] = [(FLAG.BINARY, str)] + CONVERSIONS[field_type]
TypeError: can only concatenate list (not "type") to list

**Comment by KoapT** [comment]
https://www.cnblogs.com/ydf0509/p/9538130.html
